### ISSUE TITLE
只设置上拉加载更多会崩

### ISSUE THREAD

**Issue by HuangJAndroid** [guhongya/SwipeRefreshPlush#2]
java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.VelocityTracker.addMovement(android.view.MotionEvent)' on a null object reference
                                                     at me.guhy.swiperefresh.SwipeRefreshPlus.onInterceptTouchEvent(SwipeRefreshPlus.java:516)

**Comment by guhongya** [comment]
谢谢你的问题反馈，出错原因我不是很清楚，暂时做了一个非空判断，上传了一个新的版本 'me.guhy:SwipeRefreshPlus:1.0.8-a',你可以再试下

**Comment by guhongya** [comment]
谢谢你的问题反馈，出错原因我不是很清楚，暂时做了一个非空判断，上传了一个新的版本 'me.guhy:SwipeRefreshPlus:1.0.8-a',你可以再试下 @HuangJAndroid

**Comment by HuangJAndroid** [comment]
现在滑动几次又是报java.lang.IllegalStateException: Already in the pool!
是不能放在scrollview外面吗？

**Comment by guhongya** [comment]
可以放在scrollview外面的，我又改了下'me.guhy:SwipeRefreshPlus:1.0.8-b',要不你再试试 @HuangJAndroid

**Comment by HuangJAndroid** [comment]
ok
