### ISSUE TITLE
加载更多问题

### ISSUE THREAD

**Issue by liang979zhang** [guhongya/SwipeRefreshPlush#6]
四次加载后加载更多的view无法消失了

**Comment by guhongya** [comment]
你用的那个版本的包？

**Comment by liang979zhang** [comment]
compile 'me.guhy:SwipeRefreshPlus:1.0.9-RC2' 这个

**Comment by guhongya** [comment]
你用这个试试compile 'me.guhy:SwipeRefreshPlus:1.0.9'
还有问题的话，能不能把相关代码传一下

**Comment by liang979zhang** [comment]
好的，我试试，有没有java版本的，kotlin的版本转java好多错误

**Comment by liang979zhang** [comment]
这demo运行还有错啊

**Comment by guhongya** [comment]
demo改为kotlin后没有仔细看，bug已改
